services:
  odoo:
    container_name: odoo
    image: odoo:16.0
    volumes:
      - ./addons-extra:/mnt/extra-addons
      - ./etc/odoo:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - "8069:8069"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
volumes:
  odoo-web-data:
  odoo-db-data:
    