events {
    worker_connections  1024;  # 最大连接数
}

http {
    include       mime.types;  # 包含标准的 MIME 类型定义
    default_type  application/octet-stream;  # 默认的 MIME 类型
    proxy_headers_hash_bucket_size 1024;  # 用于代理头部的哈希桶大小
    types_hash_bucket_size 1024;  # 用于 MIME 类型的哈希桶大小

    upstream web {
        server odoo:8069;  # 定义上游服务器，即 odoo 应用所在的服务器
    }

    server {
        listen 80;  # 监听 80 端口
        server_name 127.0.0.1;  # 服务器名称

        # 处理根路径请求，将所有请求代理到 Odoo
        location / {
            proxy_pass http://web;  # 将请求代理到上游服务器
            proxy_set_header Host $host;  # 设置 Host 头部
            proxy_set_header X-Real-IP $remote_addr;  # 设置真实 IP 头部
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # 设置 X-Forwarded-For 头部
            proxy_set_header X-Forwarded-Proto $scheme;  # 设置原始协议头部为当前协议
        }

        # 处理静态文件请求，显式指定静态文件目录
        location ~* /web/static/ {
            # 显式指定静态文件目录的路径，确保能正确访问
            alias /mnt/extra-addons/spiffy_theme_backend/static/;  # 替换为你的静态文件实际路径
            try_files $uri @odoo;  # 尝试本地文件，如果找不到，则交给 Odoo 处理
        }

        # 如果静态文件不存在，代理请求到 Odoo 应用
        location @odoo {
            proxy_pass http://web;  # 将请求代理到 Odoo
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
